apiVersion: v1
kind: Pod
metadata:
  name: silvestrini
  labels:
    name: silvestrini
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    args:
    - sleep
    - infinity
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "0.3"    

