apiVersion: v1
kind: Pod
metadata:
  name: silvestrini
  labels:
    name: silvestrini
spec:
  containers:
  - name: skynet
    image: nginx
    ports:
    - containerPort: 80    
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "64Mi"
        cpu: "0.3"
    
