
debug: true
server: https://control-plane01.skynet.com.br:9345
token: tokenNode
write-kubeconfig-mode: "0644"
tls-san:  
  - control-plane01.skynet.com.br
  - control-plane02.skynet.com.br
  - control-plane03.skynet.com.br

node-ip: ipNode

node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
