apiVersion: v1
kind: Pod
metadata:
  annotations:
    etcd.k3s.io/initial: '{"initial-advertise-peer-urls":"https://192.168.0.140:2380","initial-cluster":"control-plane01-d72f14dc=https://192.168.0.140:2380","initial-cluster-state":"new"}'
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
  uid: e18aa5e5b83a5a3c56d78e4054612394
spec:
  containers:
  - args:
    - --config-file=/var/lib/rancher/rke2/server/db/etcd/config
    command:
    - etcd
    env:
    - name: FILE_HASH
      value: 2213e9f20499cb9c8519e745f23675347d9d9d48e768c64d18b2e8269d65ceec
    - name: NO_PROXY
      value: .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
    - name: POD_HASH
      value: 30d0fe3c70643d8fab795ab81f52187f
    image: index.docker.io/rancher/hardened-etcd:v3.5.7-k3s1-build20230406
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: localhost
        path: /health?serializable=true
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: etcd
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext:
      privileged: false
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: localhost
        path: /health?serializable=true
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
    volumeMounts:
    - mountPath: /var/lib/rancher/rke2/server/db/etcd
      name: dir0
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/server-client.crt
      name: file0
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/server-client.key
      name: file1
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt
      name: file2
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.crt
      name: file3
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.key
      name: file4
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/peer-ca.crt
      name: file5
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/db/etcd/config
      name: file6
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  securityContext:
    seLinuxOptions:
      type: rke2_service_db_t
  volumes:
  - hostPath:
      path: /var/lib/rancher/rke2/server/db/etcd
      type: DirectoryOrCreate
    name: dir0
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/server-client.crt
      type: File
    name: file0
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/server-client.key
      type: File
    name: file1
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt
      type: File
    name: file2
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.crt
      type: File
    name: file3
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.key
      type: File
    name: file4
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/peer-ca.crt
      type: File
    name: file5
  - hostPath:
      path: /var/lib/rancher/rke2/server/db/etcd/config
      type: File
    name: file6
status: {}
