apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-rancher
  namespace: argocd-central
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          monitoring: rancher
  template:
    metadata:
      name: 'kube-prometheus-{{name}}'
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
      project: "default"
      source:
        helm:          
          valueFiles:
            - '../charts/values.yaml'            
        repoURL: https://gitlab.luizalabs.com/magalu-cloud-iaas/infrastructure/solutions/rancher-monitoring.git        
        path: 'charts'
        targetRevision: HEAD
      destination:
        server: '{{server}}'
        namespace: kube-prometheus