#
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2020 Oracle and/or its affiliates. All rights reserved.
#
# Since: January, 2020
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle Linux virtual machine.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# EXPERIMENTAL FEATURES
VAGRANT_EXPERIMENTAL="disks"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

# INSTALL PLUGIN VBguest
unless Vagrant.has_plugin?("vagrant-vbguest")
  puts 'Installing vagrant-vbguest Plugin...'
  system('vagrant plugin install vagrant-vbguest')
end

# GLOBAL BOX CONFIGURATIONS
BOX_ROCK_NAME = "generic/rocky9"

#DEFINE VM
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # GLOBAL CONFIGURATIONS
  
  ## GUEST CONFIG
  config.vbguest.no_install  = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote   = true
  config.vm.box_download_insecure=true  
  
  ## MOUNTS
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../security/", "/home/vagrant/security"
  config.vm.synced_folder "../../configs/linux/", "/home/vagrant/configs"
  config.vm.synced_folder "../../scripts/linux/", "/home/vagrant/scripts"
    
  ## PROVIDER
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true    
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

  # VM infra-server01 - DNS Bind, Postfix,Samba, NFS, Pure-FTP
  config.vm.define "infra-server01"  do |infra_server01|
    infra_server01.vm.box = BOX_ROCK_NAME
    

    # VARIABLE HOSTNAME
    VM_INFRA_SERVER01= "infra-server01"

    # HOSTNAM
    infra_server01.vm.hostname =VM_INFRA_SERVER01

    # NETWORK    
    infra_server01.vm.network "public_network", nic_type: "virtio", mac: "080027f3066a", ip: "192.168.0.130", netmask: "255.255.255.0", mode: "bridge",bridge: [
      "Intel(R) I211 Gigabit Network Connection",
      "MediaTek Wi-Fi 6 MT7921 Wireless LAN"
    ]    
    #infra_server01.vm.network "private_network", nic_type: "virtio", mac: "080027f3066b", ip: "172.36.12.230", netmask: "255.255.255.0"

    # PROVIDER
    infra_server01.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_INFRA_SERVER01
      vb.memory = 2048
      vb.cpus = 1
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    infra_server01.vm.provision "shell", name: "[Script userdata-rock.sh]", path: "../../scripts/linux/commons/userdata-rock.sh"

    # SET DNS BIND
    infra_server01.vm.provision "shell", name: "[Script userdata-bind-master.sh]", path: "../../scripts/linux/bind/userdata-bind-master.sh"

    # SET ISC DHCP
    infra_server01.vm.provision "shell", name: "[Script userdata-dhcp.sh]", path: "../../scripts/linux/dhcp/userdata-dhcp.sh"

    # CONFIGURE PURE-FTP
    infra_server01.vm.provision "shell", name: "[Script userdata-pureftp.sh]", path: "../../scripts/linux/pure-ftp/userdata-pureftp.sh"

  end

  # VM load_balancer - racher.skynet.com.br
  config.vm.define "load-balance"  do |load_balance|
    load_balance.vm.box = BOX_ROCK_NAME
    
    # VARIABLE HOSTNAME
    VM_LOAD_BALANCE= "load-balance"

    # HOSTNAM
    load_balance.vm.hostname =VM_LOAD_BALANCE

    # NETWORK
    load_balance.vm.network "public_network", nic_type: "virtio", mac: "080027f3066b", ip: "192.168.0.131", netmask: "255.255.255.0", mode: "bridge",bridge: [
      "Intel(R) I211 Gigabit Network Connection",
      "MediaTek Wi-Fi 6 MT7921 Wireless LAN"
    ]

    # PROVIDER
    load_balance.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_LOAD_BALANCE
      vb.memory = 1024
      vb.cpus = 1
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    load_balance.vm.provision "shell", name: "[Script userdata-rock.sh]", path: "../../scripts/linux/commons/userdata-rock.sh"

    # CONFIGURE NGINX LOAD BALANCE
    load_balance.vm.provision "shell", name: "[Script generate-certificates.sh]", path: "../../scripts/linux/commons/generate-certificates.sh"

    # CONFIGURE NGINX LOAD BALANCE
    load_balance.vm.provision "shell", name: "[Script userdata-load-balance.sh]", path: "../../scripts/linux/load-balance/userdata-load-balance.sh"

  end

  # Node|Control Plane Servers
  PLANES = ["control-plane01","control-plane02","control-plane03"]
  N = 2

  (0..N).each do |i|
    config.vm.define PLANES[i] do |node|
      
      # BOX NAME
      node.vm.box = BOX_ROCK_NAME
      
      # VARIABLE HOSTNAME      
      node.vm.hostname = PLANES[i]
            
      # NETWORK
      node.vm.network "public_network", mac: "080027f3067#{i}", ip: "192.168.0.14#{i}", netmask: "255.255.255.0", mode: "bridge",bridge:[
        "Intel(R) I211 Gigabit Network Connection",
        "MediaTek Wi-Fi 6 MT7921 Wireless LAN"
      ]

       #PROVIDER
      node.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.name =  PLANES[i]
        vb.memory = 8192
        vb.cpus = 3
        vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      end

      # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
      node.vm.provision "shell", name: "[Script userdata-rock.sh]", path: "../../scripts/linux/commons/userdata-rock.sh"

     # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
     node.vm.provision "shell", name: "[Script install-node.sh]", path: "../../scripts/linux/rke2/install-node.sh"
      
    end

  end  

  # Agent|Workers Servers
  WORKERS = ["worker01","worker02","worker03"]
  M = 2
  iprange = 3

  (0..M).each do |j|
    config.vm.define WORKERS[j] do |node|
      
      # BOX NAME
      node.vm.box = BOX_ROCK_NAME
      
      # VARIABLE HOSTNAME      
      node.vm.hostname = WORKERS[j]
            
      # NETWORK      
      node.vm.network "public_network", mac: "080022f3067#{j}", ip: "192.168.0.14#{iprange}", netmask: "255.255.255.0", mode: "bridge",bridge:[
        "Intel(R) I211 Gigabit Network Connection",
        "MediaTek Wi-Fi 6 MT7921 Wireless LAN"
      ]
      iprange += 1

       #PROVIDER
      node.vm.provider "virtualbox" do |vb|        
        vb.name =  WORKERS[j]
        vb.memory = 8192
        vb.cpus = 3        
      end

      # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
      node.vm.provision "shell", name: "[Script userdata-rock.sh]", path: "../../scripts/linux/commons/userdata-rock.sh"
      
      # INSTAL RKE2 AGENT
      node.vm.provision "shell", name: "[Script install-agent.sh]", path: "../../scripts/linux/rke2/install-agent.sh"
      
    end    

  end  

  # # VM debian_client 
  # config.vm.define "debian-client01"  do |debian_client01|
  #   debian_client01.vm.box = BOX_ROCK_NAME

  #   # VARIABLE HOSTNAME
  #   VM_DEBIAN_CLIENT01= "debian-client01"

  #   # HOSTNAME
  #   debian_client01.vm.hostname =VM_DEBIAN_CLIENT01

  #   # NETWORK
  #   debian_client01.vm.network "public_network", mac: "080027f3096a" ,ip: "192.168.0.150",mode: "bridge",bridge: [
  #     "Intel(R) I211 Gigabit Network Connection",
  #     "MediaTek Wi-Fi 6 MT7921 Wireless LAN"
  #   ]
  #   #debian_client01.vm.network "private_network",type: "dhcp",ip: "172.36.12.1",mac: "080027f3096b"

  #   # MOUNTS  
  #   debian_client01.vm.synced_folder "../../test/linux/", "/home/vagrant/test"

  #   #PROVIDER
  #   debian_client01.vm.provider "virtualbox" do |vb|
  #     vb.linked_clone = true
  #     vb.name =VM_DEBIAN_CLIENT01
  #     vb.memory = 8192
  #     vb.cpus = 3
  #     vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  #   end

  #   # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
  #   debian_client01.vm.provision "shell", path: "../../scripts/linux/commons/userdata-debian.sh"

  #   # INSTALL DOCKER
  #   debian_client01.vm.provision "shell", path: "../../scripts/linux/kubernetes/install.sh"

  #   # CREATE DOCKER IMAGE FOR TESTING
  #   debian_client01.vm.provision "shell", path: "../../scripts/linux/docker/create-docker-image.sh"

  #   # CHECK DOCKER IMAGE
  #   debian_client01.vm.provision "shell", path: "../../scripts/linux/docker/check-docker-image.sh"

  # end

end