# https://github.com/rancher/server-chart/blob/master/rancher/values.yaml

hostname: rancher.skynet.com.br
ingress:
  enabled: true
  ingressClassName: "nginx"
  tls:
    # options: rancher, letsEncrypt, secret
    source: rancher
    secretName: tls-rancher-ingress      
    bootstrapPassword: "Skynet@123456"