apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: consul

  project: default

  source:
    repoURL: https://github.com/hashicorp/consul-k8s
    targetRevision: main
    path: charts/consul

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  chart:
    values: values.yaml
