apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: consul

  project: default

  source:
    repoURL: https://github.com/hashicorp/consul-k8s
    targetRevision: main
    path: charts/consul

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  chart:
    values: |
      global:
        nameOverride: consul
        fullnameOverride: consul

      server:
        enabled: true

      ui:
        enabled: true

      client:
        enabled: true

      connectInject:
        enabled: true

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx # Substitua pela classe do ingress desejada
    hosts:
      - consul.skynet.com.br
    paths:
      - /
    tls: []
