apiVersion: v1
entries:
  app-silvestrini:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-11-21T21:04:09.9686086-03:00"
    description: A Helm chart for Kubernetes
    digest: b63c9ad1c397aee061fd5622c19bd76599ea4c8932af136e536f61bd38336b9d
    name: app-silvestrini
    type: application
    urls:
    - https://github.com/marcossilvestrini/learning-kubernetes/app-silvestrini-0.1.0.tgz    
    version: 0.1.0
generated: "2023-11-21T21:04:09.9676086-03:00"
