apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
spec:
  chart:
    version: "7.2.1" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/0.8.1/CHART_VERSIONS
    values:
      global:
        hosts:
          domain: gitlab.skynet.com.br # use a real domain here
        ingress:
          configureCertmanager: true
      certmanager-issuer:
        email: mr.durock01@gmail.com # use your real email address here
