apiVersion: v1
kind: PersistentVolume
metadata: #
  name: data-gitlab-postgresql-0
  labels:
    storage: nfs
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: infra-server01
    path: "/var/nfs/gitlab/data-gitlab-postgresql-0"
  storageClassName: nfs