apiVersion: v1
kind: PersistentVolume
metadata: #
  name: gitlab-minio
  labels:
    storage: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: infra-server01
    path: "/var/nfs/gitlab/gitlab-minio"
  storageClassName: nfs