apiVersion: v1
kind: PersistentVolume
metadata: #
  name: repo-data-gitlab-gitaly-0
  labels:
    storage: nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: infra-server01
    path: "/var/nfs/gitlab/repo-data-gitlab-gitaly-0"
  storageClassName: nfs