apiVersion: v1
kind: PersistentVolume
metadata: #
  name: redis-data-gitlab-redis-master-0
  labels:
    storage: nfs
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: infra-server01
    path: "/var/nfs/gitlab/redis-data-gitlab-redis-master-0"
  storageClassName: nfs