apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  destination:
    namespace: consul
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/marcossilvestrini/learning-kubernetes.git
    targetRevision: HEAD
    path: 
        charts/consul        
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
        - template/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
