apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul-application  
  namespace: argocd
spec:
  destination:
    namespace: consul
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/hashicorp/consul-k8s
    targetRevision: main
    path: charts/consul
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
