apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      hostPort: 9001      
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"      
      requests:
        memory: "64Mi"
        cpu: "0.3"     
    volumeMounts:
    - name: my-pvc
      mountPath: /usr/share/nginx/html    
  volumes:
  - name: my-pvc
    persistentVolumeClaim:
      claimName: my-pvc