apiVersion: v1
kind: Pod
metadata:
  namespace: silvestrini
  name: silvestrini
  labels:
    name: silvestrini 
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    args:
    - sleep
    - infinity
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "0.3"
    volumeMounts: # lista de volumes que serão montados no container
    - name: first-emptydir # nome do volume
      mountPath: /silvestrini # diretório onde o volume será montado 
    args:
      - sleep
      - infinity  
  volumes: # lista de volumes
  - name: first-emptydir # nome do volume
    emptyDir: # tipo do volume
      sizeLimit: 256Mi # tamanho máximo do volume    

