apiVersion: v1
entries:
  app-silvestrini:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-11-21T20:42:10.3679116-03:00"
    description: A Helm chart for Kubernetes
    digest: e30596438c48d366d442262bbb04383b5f0c49c71d38e3c5d5c43869d66a0047
    name: app-silvestrini
    type: application
    urls:
    - https://github.com/marcossilvestrini/learning-kubernetes/blob/main/charts/app-silvestrini/app-silvestrini-0.1.0.tgz
    version: 0.1.0
generated: "2023-11-21T20:42:10.3669114-03:00"
