apiVersion: v1
kind: Service # Tipo do objeto, no caso, um Service
metadata:
  name: clusterip-app-silvestrini
spec:
  selector: # Seleciona os Pods que serão expostos pelo Service
    app: app-silvestrini # Neste caso, os Pods com o label app=my-app
  ports:
    - protocol: TCP
      port: 80 # Porta do Service
      targetPort: 9001 # Porta dos Pods
