apiVersion: v1
kind: Service
metadata:
  name: nodeport-app-silvestrini
spec:
  type: NodePort # Tipo do Service
  selector:
    app: app-silvestrini
  ports:
    - protocol: TCP
      port: 80 # Porta do Service, que será mapeada para a porta 8080 do Pod
      targetPort: 9002 # Porta dos Pods
      nodePort: 30080   # Porta do Node, que será mapeada para a porta 80 do Service