# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

## Argo CD configuration
## Ref: https://github.com/argoproj/argo-cd
##

nameOverride: argocd

## Globally shared configuration
global:  
  domain: argocd.skynet.com.br
  logging:
    format: text    
    level: info

## Argo Configs
configs:  
  cm:    
    url: "https://argocd.skynet.com.br"
    accounts.skynet: apiKey, login
    
  # Argo CD configuration parameters
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
  params:   
    server.insecure: true    
    applicationsetcontroller.policy: create-only

  # Argo CD RBAC policy configuration
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
  rbac:
    create: true  
    policy.default: 'role:admin'
    policy.csv: |
        p, skynet, applications, create, */*, allow
        p, skynet, applications, update, */*, allow
        p, skynet, applications, delete, */*, allow
        p, skynet, applications, sync, */*, allow
        p, skynet, applications, override, */*, allow
        p, skynet, applications, action/*, */*, allow
        p, skynet, applicationsets, get, */*, allow
        p, skynet, applicationsets, create, */*, allow
        p, skynet, applicationsets, update, */*, allow
        p, skynet, applicationsets, delete, */*, allow
        p, skynet, certificates, create, *, allow
        p, skynet, certificates, update, *, allow
        p, skynet, certificates, delete, *, allow
        p, skynet, clusters, create, *, allow
        p, skynet, clusters, update, *, allow
        p, skynet, clusters, delete, *, allow
        p, skynet, repositories, create, *, allow
        p, skynet, repositories, update, *, allow
        p, skynet, repositories, delete, *, allow
        p, skynet, projects, create, *, allow
        p, skynet, projects, update, *, allow
        p, skynet, projects, delete, *, allow
        p, skynet, accounts, update, *, allow
        p, skynet, gpgkeys, create, *, allow
        p, skynet, gpgkeys, delete, *, allow
        p, skynet, exec, create, */*, allow
 
  # Argo CD sensitive data
  # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#sensitive-data-and-sso-client-secrets
  secret:    
    # -- Bcrypt hashed admin password
    ## Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
    ## `htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/'`
    argocdServerAdminPassword: "$2a$10$1PwBWvXXUsl235gMWA8JIukpzjfC9o3jcjlZR2wNWNhjkYhP840PW"
    

## Server
server:
  ingress:    
    enabled: true    
    ingressClassName: "nginx"
    hosts: 
      - argocd.skynet.com.br    
    paths:
      - /    
    pathType: Prefix        
    tls:
      - secretName: argocd-secret
        hosts:
          - argocd.skynet.com.br    
    https: true 