apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-rancher
  namespace: argocd-central
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          monitoring: rancher
  template:
    metadata:
      name: 'kube-prometheus-{{name}}'
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
      project: "default"
      source:
        helm:
          # ignoreMissingValueFiles: true faz com que ignore values não encontrados,
          # a exemplo situações onde não queremos ter um values.yaml customizados
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - '../{{name}}/values.yaml' # procura values.yaml customizados
        repoURL: https://github.com/marcossilvestrini/learning-kubernetes.git
        path: 'kube-prometheus/applicationset/default'
        targetRevision: HEAD
      destination:
        server: '{{server}}'
        namespace: kube-prometheus