name: Check Web App Status

on:
  push:
    branches:
      - main

jobs:
  check_status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install axios

    - name: Check Web App Status
      run: |
        # Importando a biblioteca axios para fazer a solicitação HTTP
        const axios = require('axios');

        async function checkWebAppStatus() {
          const url = 'http://app-silvestrini.skynet.com.br/';
          try {
            const response = await axios.get(url);
            if (response.status === 200) {
              console.log('A Web App está online e funcionando corretamente.');
            } else {
              throw new Error(`A Web App retornou um código de status inesperado: ${response.status}`);
            }
          } catch (error) {
            console.error(`Houve um problema ao verificar o status da Web App: ${error.message}`);
            process.exit(1);
          }
        }

        checkWebAppStatus();
