key:
  components:
    - name: app-silvestrini
      chart: app-silvestrini
      version: "1.1.2"
      releaseName: app-silvestrini      
      repoUrl: "https://marcossilvestrini.github.io/learning-helm"
      namespace: app-silvestrini
      values: |
        replicaCount: 3
        image:
          repository: mrsilvestrini/app-silvestrini
          pullPolicy: IfNotPresent          
          tag: "v1.0.0"
        serviceAccount:          
          create: true
        service:
          type: ClusterIP
          port: 80
        ingress:
          enabled: true
          className: ""
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hosts:
            - host: app-silvestrini.skynet.com.br
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: []
          #  - secretName: chart-example-tls
          #    hosts:
          #      - chart-example.local
        resources:  
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        autoscaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 6
          targetCPUUtilizationPercentage: 80
          # targetMemoryUtilizationPercentage: 80
            