# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

# kubectl delete crd alertmanagerconfigs.monitoring.coreos.com
# kubectl delete crd alertmanagers.monitoring.coreos.com
# kubectl delete crd podmonitors.monitoring.coreos.com
# kubectl delete crd probes.monitoring.coreos.com
# kubectl delete crd prometheusagents.monitoring.coreos.com
# kubectl delete crd prometheuses.monitoring.coreos.com
# kubectl delete crd prometheusrules.monitoring.coreos.com
# kubectl delete crd scrapeconfigs.monitoring.coreos.com
# kubectl delete crd servicemonitors.monitoring.coreos.com
# kubectl delete crd thanosrulers.monitoring.coreos.com

key:
  components:
    - name: kube-prometheus
      chart: kube-prometheus-stack
      version: "55.3.0"
      releaseName: kube-prometheus      
      repoUrl: "https://prometheus-community.github.io/helm-charts"      
      namespace: kube-prometheus
      values: |
        alertmanager:
          enabled: true
          externalUrl: https://alertmanager.skynet.com.br
          ingress:
            enabled: true
            hosts:
              - alertmanager.skynet.com.br
            tls:
              - secretName: alertmanager-tls
                hosts:
                  - alertmanager.skynet.com.br
          alertmanagerspec:
            volumeClaimTemplate:
              spec:
                storageClassName: longhorn
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 10Gi                   
        prometheus:
          ingress:
            enabled: true
            hosts:
              - prometheus.skynet.com.br
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.skynet.com.br
          prometheusspec:
            volumeClaimTemplate:
              spec:
                storageClassName: longhorn
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 10Gi                             
        grafana:
          ingress:
            enabled: true
            adminPassword: "Skynet@123456"
            hosts:
              - grafana.skynet.com.br
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.skynet.com.br
          grafanaspec:
            volumeClaimTemplate:
              spec:
                storageClassName: longhorn
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 10Gi                             
