# https://github.com/rancher/rancher/blob/release/v2.9/chart/values.yaml

key:
  components:  
    - name: rancher
      chart: rancher
      version: "2.8.2"
      releaseName: rancher
      repoUrl: "https://releases.rancher.com/server-charts/latest"
      namespace:  cattle-system
      values: |
        hostname: rancher.skynet.com.br
        ingress:
          enabled: true
          ingressClassName: "nginx"
          tls:
          # options: rancher, letsEncrypt, secret
            source: rancher
            secretName: tls-rancher-ingress      
        bootstrapPassword: "Skynet@123456"  
