key:
  components:  
    - name: rancher
      chart: rancher
      version: "2.7.9"
      releaseName: rancher
      repoUrl: "https://github.com/rancher/server-chart"                     
      namespace:  cattle-system
      values: |
        hostname: rancher.skynet.com.br