key:
  components:  
    - name: metallb
      chart: metallb
      version: "4.7.15"
      releaseName: metallb
      repoUrl: "https://charts.bitnami.com/bitnami"      
      namespace: metallb
    
    - name: longhorn
      chart: longhorn/longhorn
      version: "1.6.0-dev"
      releaseName: longhorn
      repoUrl: "https://charts.longhorn.io"      
      namespace: longhorn

    - name: app-silvestrini
      chart: app-silvestrini
      version: "1.1.2"
      releaseName: app-silvestrini
      repoUrl: "https://marcossilvestrini.github.io/learning-helm"
      namespace: app-silvestrini