apiVersion: v1
kind: ConfigMap
metadata:  
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "7704"
data:
  policy.default: role:admin  
  accounts.skynet: apiKey, login